// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/formulate-reply.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
var SYSTEM_PROMPT = `Voc\xEA \xE9 a Dra. J\xE9ssica Carpaneda (CRM GO 31189), psiquiatra. Responda SEMPRE em primeira pessoa ("eu"), tom acolhedor, profissional e humano. Sem jarg\xF5es. N\xE3o fa\xE7a diagn\xF3sticos por mensagem. Valores atuais: Primeira consulta R$ 400 (90 min); Retorno R$ 250 (60 min); Renova\xE7\xE3o de receita R$ 150 (caso excepcional, apenas para pacientes j\xE1 acompanhados quando n\xE3o conseguir atender). Site: drajessicacarpaneda.com.br. P\xFAblico adulto. Em risco iminente, oriente CVV 188 / SAMU 192 / emerg\xEAncia mais pr\xF3xima.`;
var SYSTEM_PROMPT_OPINIAO = `Voc\xEA \xE9 a Dra. J\xE9ssica Carpaneda. Responda a uma avalia\xE7\xE3o p\xFAblica no Doctoralia em primeira pessoa, agradecendo, mantendo sigilo m\xE9dico (nunca confirmar v\xEDnculo, nunca citar dados cl\xEDnicos), tom breve e humano.`;
var SYSTEM_PROMPT_NOVIDADE = `Voc\xEA \xE9 a Dra. J\xE9ssica Carpaneda. Escreva uma "Novidade" para o Doctoralia em primeira pessoa, at\xE9 750 caracteres, sem jarg\xF5es, sem tra\xE7os longos, linguagem direta e acolhedora que capte o paciente.`;
var formulate_reply_default = defineTool({
  name: "formulate_reply",
  title: "Formular resposta",
  description: "Gera uma resposta em primeira pessoa (Dra. J\xE9ssica) para WhatsApp, opini\xE3o p\xFAblica do Doctoralia, ou Novidade do perfil.",
  inputSchema: {
    message: z.string().min(1).describe("Mensagem/contexto recebido ou tema da Novidade."),
    mode: z.enum(["whatsapp", "opiniao", "novidade"]).default("whatsapp").describe("Tipo de resposta a gerar.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ message, mode }) => {
    const key = process.env.LOVABLE_API_KEY;
    if (!key) return { content: [{ type: "text", text: "LOVABLE_API_KEY ausente." }], isError: true };
    const system = mode === "opiniao" ? SYSTEM_PROMPT_OPINIAO : mode === "novidade" ? SYSTEM_PROMPT_NOVIDADE : SYSTEM_PROMPT;
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", "Lovable-API-Key": key },
      body: JSON.stringify({
        model: "google/gemini-3-flash-preview",
        messages: [{ role: "system", content: system }, { role: "user", content: message }]
      })
    });
    if (!res.ok) return { content: [{ type: "text", text: `Erro do gateway: ${res.status}` }], isError: true };
    const data = await res.json();
    const text = data?.choices?.[0]?.message?.content ?? "";
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var SERVICES = [
  { nome: "Primeira consulta", duracao_min: 90, valor_brl: 400, obs: "Avalia\xE7\xE3o inicial ampla." },
  { nome: "Retorno", duracao_min: 60, valor_brl: 250, obs: "Seguimento de pacientes j\xE1 em acompanhamento." },
  { nome: "Renova\xE7\xE3o de receita", duracao_min: 15, valor_brl: 150, obs: "Caso excepcional, apenas para pacientes j\xE1 acompanhados quando n\xE3o conseguir atender presencialmente. Receitas normalmente exigem consulta." }
];
var list_services_default = defineTool2({
  name: "list_services",
  title: "Listar servi\xE7os e valores",
  description: "Retorna os servi\xE7os atuais da Dra. J\xE9ssica com dura\xE7\xE3o, valor em BRL e observa\xE7\xF5es.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
var INFO = {
  nome: "Dra. J\xE9ssica Carpaneda",
  especialidade: "Psiquiatria (adultos)",
  crm: "CRM GO 31189",
  site: "https://drajessicacarpaneda.com.br",
  publico: "Adultos",
  emergencia: { cvv: "188", samu: "192" }
};
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Informa\xE7\xF5es profissionais",
  description: "Retorna dados p\xFAblicos da Dra. J\xE9ssica (nome, CRM, site, p\xFAblico atendido, canais de emerg\xEAncia).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(INFO, null, 2) }],
    structuredContent: INFO
  })
});

// src/lib/mcp/index.ts
var projectRef = "faripwgamoymvjdanvpf";
var mcp_default = defineMcp({
  name: "dra-jessica-mcp",
  title: "Dra. J\xE9ssica \u2014 Protocolo de Atendimento",
  version: "0.1.0",
  instructions: "Ferramentas do consult\xF3rio da Dra. J\xE9ssica Carpaneda (psiquiatra). Use `formulate_reply` para gerar respostas em primeira pessoa (WhatsApp, opini\xE3o p\xFAblica ou Novidade Doctoralia), `list_services` para valores/dura\xE7\xE3o e `get_contact_info` para dados profissionais.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [formulate_reply_default, list_services_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
